baseurl = "https://binayadevimakhim.com.np"
title = "Bukiphool"
author = "Bina Makhim"
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true



[params]
author = "बुकी फूल"
introDescription = "THE FLOWER OF MOUNTAIN"

[social]
instagram = "biochemicalmind"
linkedin = "binaya-devi-makhim-77301031a"
twitter = "biochemicalmind"
